### ISSUE TITLE
Spectrometer: Notifiers

### ISSUE THREAD

**Issue by aspitarl** [MHDLab/Acquisition#1]
Need to clean up the data acquisition of spectrometers in trigger mode. The spectrometers end up taking a bunch of empty data which makes analysis harder when you remove empty channels as the time array needs to be trimmed as well.

**Comment by aspitarl** [comment]
@msb002 While revamping the spectrometer data acqusition, the final calibration data (rad per counts) should be added into the global channel, along with the path to the full calibration tdms file

**Comment by msb002** [comment]
Done and done. The calibration file path is being saved as a property of the calibration data. Everything is running much smoother.

**Comment by msb002** [comment]
Spectrometers are acquiring before multiplexer is done switch. I think its because it's reading it's own notifiers, so I will try to return to the old way of using notifiers and test it.

This will never end.

**Comment by aspitarl** [comment]
Maybe you could poll the multiplexer and wait until it does not return a "-1"? I vaguely feel like I did that before.

**Comment by msb002** [comment]
REsolved in latest commit
