### ISSUE TITLE
Multiplexer autoswitching loses control with short wait time

### ISSUE THREAD

**Issue by aspitarl** [MHDLab/Acquisition#2]
I found that I had to extend the wait time to ~10 s between multiplexer switches to get the switching to be stable. For the shorter default time I would eventually get a -1 back from the multiplexer.

**Comment by msb002** [comment]
Recent updates to the notifiers should've resolved this issue. Haven't tested with long measurements, but works with 250ms switching. Reopen the issue if you find it persists.
